spring:
  datasource:
    url: jdbc:sqlserver://technogadgetsphserver.database.windows.net:1433;database=technogadgetsph_db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: dhanjrt26
    password: '@GitHub1'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191